CO 1076 add query params for parking space
osu-mist/locations-frontend-api pull request #55
Opened 2018-04-24 00:01 UTC by tsoliangwu0130

2018-04-25 15:10 UTC, jaredkosanovic requested changes

2018-04-25 15:10 UTC, jaredkosanovic commented on swagger.yaml
> +        - in: query
Could you make the names and descriptions of these new query parameters more detailed? For example, what are your thoughts about making them called the same as the fields that relate to? (adaParkingSpaceCount, etc.)

2018-04-25 15:10 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/locations/frontend/db/LocationDAO.groovy
> +            query.must(QueryBuilders.rangeQuery("attributes.adaParkingSpaceCount").gt(ada))
What do you think making this a greater than or equal to instead? If I want parking lots with 1 or more ada parking spaces (or moto or ev, etc.) then I would need to put in an `ada` parameter of 0, but that returns every location (ones with `null` for the ada space count too).

2018-04-25 15:23 UTC, tsoliangwu0130 commented on src/main/groovy/edu/oregonstate/mist/locations/frontend/db/LocationDAO.groovy
> +            query.must(QueryBuilders.rangeQuery("attributes.adaParkingSpaceCount").gt(ada))
Good catch. Will fix.

2018-04-26 16:54 UTC, jaredkosanovic approved these changes

2018-04-26 20:50 UTC, merged