Feature/co 1012
osu-mist/locations-frontend-api pull request #60
Opened 2018-06-22 18:59 UTC by adpextwindong

I refactored the mapping logic so all of the JSON handling fits in one screen.
I also added a docopt at the top so the command line arguments are easier to understand for a first time user.
Added a requirements.txt for the docopt import.

2018-06-22 21:33 UTC, tsoliangwu0130 requested changes
The code looks good, there are only a few [PEP8](https://www.python.org/dev/peps/pep-0008/) warnings. Could you fix these warning?

2018-06-22 21:33 UTC, tsoliangwu0130 commented on DataDiscrepancyUtil/dataDiffCheck.py
> +            with open(args['<new_data_path>'], "r") as new_json_file:
You could open multiple files like this:

```python
with open('a', 'w') as a, open('b', 'w') as b:
    do_something()
```

https://stackoverflow.com/questions/4617034/how-can-i-open-multiple-files-using-with-open-in-python

2018-06-22 21:33 UTC, tsoliangwu0130 commented on DataDiscrepancyUtil/dataDiffCheck.py
> +
According to PEP8 standard, module level import should be at top of the file. See error [E402](http://pep8.readthedocs.io/en/release-1.7.x/intro.html#error-codes).

2018-06-22 21:33 UTC, tsoliangwu0130 commented on DataDiscrepancyUtil/dataDiffCheck.py
>                  if rekeyCheckDict.has_key(bname):
`has_key` has been deprecated, instead, we should use `in` here.

2018-06-26 19:25 UTC, gmtcrary commented
Fixed, @tsoliangwu0130.

2018-06-26 19:26 UTC, gmtcrary commented on DataDiscrepancyUtil/dataDiffCheck.py
> +            with open(args['<new_data_path>'], "r") as new_json_file:
Thanks for showing me this!

2018-06-26 20:13 UTC, tsoliangwu0130 approved these changes
Looks good!

2018-06-26 21:28 UTC, merged